### ISSUE TITLE
new mount

### ISSUE THREAD

**Issue by robthide37** [MrSuntoryTime/user-mod#2]
hey i have newer mount if you want that has lgx and better compact for the modular mount and you can base yours off the newer one or ill make a repo for all the parts so you can link yours to it or contribute if you want. lmk how want do it or I can just pm link to the newer stuff but I want get off drive anyway

**Comment by MrSuntoryTime** [comment]
Hey Rob, yeah im down to put everything into one consolidated place. lmk how i should do that.

send me the file if you have a chance.

Thanks Rob, good to hear from you.

**Comment by robthide37** [comment]
I can send you through teams or just I can do drive links to get them to
you . maybe I can do pull request not sure ill take look . And thanks ya it
was shitty stuff to deal with on my end but its life .

**Comment by MrSuntoryTime** [comment]
Yeah man, life really throws some mean curveballs... 

I just sent you a DM on teams.
